import 'dotenv/config';
import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';

import { registerBoundaryRoutes } from './server/boundaryRoutes';
import { registerWeatherRoutes } from './server/weatherRoutes';
import { registerPushRoutes } from './server/pushRoutes';
import { registerCellRoutes } from './server/cellRoutes';
import { registerRouteRoutes } from './server/routeRoutes';
import { registerAlertRoutes, startAlertIngest } from './server/alertIngest';
import { registerFireRoutes } from './server/fireRoutes';

/**
 * One process serves both the API and the client.
 *
 * In development Vite runs as middleware; in production we serve the built
 * bundle from dist/ with an SPA fallback.
 *
 * REMOVED: /api/camping-ai
 * That endpoint asked a language model to invent dispersed campsites, complete
 * with coordinates. Hallucinated coordinates send somebody down a forest road
 * to a site that does not exist, which is the exact failure this app exists to
 * prevent. Campsites now come only from the curated dataset, OpenStreetMap,
 * and other campers.
 */
const startServer = async (): Promise<void> => {
  const app = express();
  const PORT = Number(process.env.PORT) || 3000;
  const isProduction = process.env.NODE_ENV === 'production';

  app.disable('x-powered-by');
  app.use(express.json({ limit: '256kb' }));

  app.get('/api/health', (_req, res) => {
    res.json({ status: 'ok', app: 'Wandrlust' });
  });

  // Public land boundaries — three authoritative government ArcGIS services.
  registerBoundaryRoutes(app);

  // Weather plus fire / flood / storm alerts (NWS + Environment Canada).
  registerWeatherRoutes(app);

  // Web Push delivery.
  registerPushRoutes(app);

  // Approximate cell coverage by carrier. Inert without OPENCELLID_API_KEY.
  registerCellRoutes(app);

  // Routing. Tries engines that can drive a forest road before ones that can't.
  registerRouteRoutes(app);

  // The connection to the issuing agencies: polls NWS and Environment
  // Canada, stores what they publish, and lets the SQL matcher push it.
  registerAlertRoutes(app);

  // Active wildfire data, US (WFIGS perimeters) + Canada (FireRadar points).
  // No API key on either side; the response is a unified GeoJSON that the
  // client can style as two distinct things (perimeters in red, points
  // in orange) without needing to know which country a fire came from.
  registerFireRoutes(app);

  // State/province outlines and the land-vs-water test are deliberately
  // NOT routes. Both ship as prebuilt files in public/map/, generated by
  // scripts/buildMapAssets.ts, because the source datasets are far too
  // big to fetch inside a serverless request and the client needs both
  // answers instantly and offline. See those files for the full story.

  // Unknown API routes must return JSON, not the SPA's index.html — otherwise
  // a typo in a fetch URL shows up in the client as "unexpected token <".
  app.use('/api', (_req, res) => {
    res.status(404).json({ error: 'Unknown endpoint' });
  });

  if (!isProduction) {
    const vite = await createViteServer({
      server: { middlewareMode: true, host: '0.0.0.0', port: PORT },
      appType: 'spa'
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');

    /**
     * Cache lifetimes, which the app's ability to update depends on.
     *
     * A blanket one-hour max-age used to apply to everything here, including
     * sw.js. A service worker the browser refuses to re-fetch for an hour is
     * an app that can't tell anyone a new version exists — so the worker and
     * the HTML document are explicitly revalidated every time, while the
     * content-hashed bundles are cached hard because their names change
     * whenever their contents do.
     *
     * Vercel applies the equivalent rules from vercel.json in production;
     * these keep a self-hosted `npm start` behaving the same way.
     */
    app.use(
      express.static(distPath, {
        index: false,
        setHeaders: (res, filePath) => {
          const name = path.basename(filePath);

          if (name === 'sw.js') {
            res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
            res.setHeader('Service-Worker-Allowed', '/');
            return;
          }
          if (name === 'manifest.webmanifest') {
            res.setHeader('Content-Type', 'application/manifest+json; charset=utf-8');
            res.setHeader('Cache-Control', 'public, max-age=0, must-revalidate');
            return;
          }
          if (filePath.includes(`${path.sep}assets${path.sep}`)) {
            res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
            return;
          }
          res.setHeader('Cache-Control', 'public, max-age=3600');
        }
      })
    );

    // SPA fallback. Must also serve /auth/callback so the OAuth redirect
    // reaches the client and the PKCE exchange can complete.
    app.get('*', (_req, res) => {
      // Never cached: this document is what points at the current bundle, so
      // a stale copy pins the user to an old build.
      res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  // Last-resort handler: log the detail, tell the client nothing useful.
  app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    console.error('Unhandled server error:', err.message);
    res.status(500).json({ error: 'Something went wrong' });
  });

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Wandrlust running on http://0.0.0.0:${PORT}`);
    // Poll the agencies on a timer so pushed warnings need no external cron.
    startAlertIngest(`http://127.0.0.1:${PORT}`);
  });
};

startServer().catch((err) => {
  console.error('Failed to start server:', err);
  process.exit(1);
});
